// INMEDIATELY INVOKED FUNCTION EXPRESSION
// GLOBAL SCOPE KE POLLUTION SE PROBLEM HOTI HAI KAYI BAAR TOH USKE DECLARATION AND VARIABLES KO
// HATANE KE LIYE HAMNE IIFE KA USE KARTE HAI
// SUDDEN IMPLEMENTATION OCCURS

(function one () {
    console.log(`DB  CONNECTED`)
})();


(() => {
    console.log(`DB connected to server`);
})()